server:
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbName: cars_sale
  sslMode: disable
  MaxOpenConn: 100
  MaxIdleConn: 15
  MaxConnLifeTime: 5
  MaxConnIdleTime: 5
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
password:
  UpperChars: true
  LowerChars: true
  InputNum: true
  InputSpecials: true
  MinLength: 8
  MaxLength: 24
