server:
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: 123456
  dbName: car_sale
  sslMode: false
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240
password:
  UpperChars: true
  LowerChars: true
  InputNum: true
  InputSpecials: true
  MinLength: 8
  MaxLength: 24
